services:
  - type: web
    name: tusoin-finanzas
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MASTER_ADMIN_EMAIL
        value: Admin2027@tusoinrd.com
      - key: MASTER_ADMIN_PASSWORD
        value: AdminD&J2027
      - key: ALLOWED_GOOGLE_EMAILS
        value: gerencia@tusoinrd.com,admin@tusoinrd.com,tusoin.rd@gmail.com
      - key: DATABASE_URL
        fromDatabase:
          name: tusoin-db
          property: connectionString

databases:
  - name: tusoin-db
    plan: free
    databaseName: tusoin_db
    user: tusoin_user
